Starting optimized decision tree processing...
Traceback (most recent call last):
  File "c:\Users\ETERRAF\Downloads\EB_CL\Main.py", line 193, in <module>
    main()
    ~~~~^^
  File "c:\Users\ETERRAF\Downloads\EB_CL\Main.py", line 155, in main
    return main_optimized()
  File "c:\Users\ETERRAF\Downloads\EB_CL\Main.py", line 114, in main_optimized
    data_fin_processed = arbre_dec_optimized(data_fin, data, data_annexe)
  File "c:\Users\ETERRAF\Downloads\EB_CL\utils\functions_optimized.py", line 496, in arbre_dec_optimized
    data_fin = data_fin.reset_index(drop=False)
  File "C:\Users\ETERRAF\Documents\anaconda3\Lib\site-packages\pandas\core\frame.py", line 6472, in reset_index        
    new_obj.insert(
    ~~~~~~~~~~~~~~^
        0,
        ^^
    ...<2 lines>...
        allow_duplicates=allow_duplicates,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ETERRAF\Documents\anaconda3\Lib\site-packages\pandas\core\frame.py", line 5158, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert id_pm, already exists
